name: bonfire_test
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bonfire: ^3.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/tiled/
    - assets/images/vendor/CuteFantasyFree/
    - assets/images/vendor/CuteFantasyFree/Tiles/
    - assets/images/vendor/CuteFantasyFree/Player/
